train:
  experiment_name: 'n_allfull_lr$lr_$schedule_$optim_100k'

  # Model
  model:
    sam_name: 'text_sam'
    params:
      # Fix the a part of parameters in SAM
      img_en_type: 'full'
      prompt_en_type: 'full'
      mask_de_type: 'full'
      enhance_proj: False
      ckpt_path: 'sam_ckpt/sam_vit_b_01ec64.pth'
      model_type: 'vit_b'    # type should be in [vit_h, vit_b, vit_l, default]

  # Dataset
  dataset:
    name: 'torch_voc_text_full'
    params:
      root: '/hdd0/lzr/'
      year: '2012'
      image_set: 'train'
      filter_keywords:
      - background
    transforms:
      resize:
        params:
          size: [1024, 1024]
      to_tensor:
        params: ~
    target_transforms:
      resize:
        params:
          size: [1024, 1024]

  # Losses
  losses:
    bce:
      weight: 0.5
      params:

  # Optimizer
  opt_params:
    lr_default:  $lr
    wd_default: 0.0
    momentum: 0.9
    lr_list:  [ ]
    group_keys: [ ]
    wd_list:  [ ]
  opt_name: '$optim' # 'sgd'
  scheduler_name: '$schedule'

  # Runner
  max_iter: 100000
  log_iter: 20
  eval_iter: 200
  runner_name: 'text_runner'
  # Dataloader
  bs: 2 # 8
  num_workers: 2
  drop_last: True
  # Logger
  use_tensorboard: True
  tensorboard_folder: './experiment/tensorboard'
  log_folder: './experiment/log'
  model_folder: './experiment/model'

val:
  # Dataset
  dataset:
    name: 'torch_voc_text_full'
    params:
      root: '/hdd0/lzr/'
      year: '2012'
      image_set: 'val'
      filter_keywords:
      - background
    transforms:
      resize:
        params:
          size: [1024, 1024]
      to_tensor:
        params: ~
    target_transforms:
      resize:
        params:
          size: [1024, 1024]

  bs: 2
  num_workers: 2
  drop_last: True


test:
  need_test: False

